<?php

// Exit if accessed directly
if (!defined('ABSPATH')) exit;

function asp_options_array() {
    return [
        'asp-general-settings' => [
            'asp_general_sermon_layout',
            'asp_general_date_format',
            'asp_general_archive_slug',
            'asp_general_archive_option',
            'asp_general_archive_page',
            'asp_general_sermon_label',
            'asp_general_speaker_label',
            'asp_general_book_label',
            'asp_general_disable_plural',
            'asp_general_topic_label',
            'asp_general_toolbar_menu',
            'asp_general_disable_view_count',
            'asp_general_block_editor',
        ],
        'asp-design-settings' => [
            'asp_design_body_color',
            'asp_design_element_background',
            'asp_design_heading_h1_color',
            'asp_design_heading_h1_size',
            'asp_design_heading_h1_height',
            'asp_design_heading_h1_weight',
            'asp_design_title_padding',
            'asp_design_sermon_image',
            'asp_design_hide_featured_image',
            'asp_design_title_overlay_opacity',
            'asp_design_disable_sermon_title_image',
            'asp_design_disable_sermon_title',
            'asp_design_custom_css',
            'asp_design_archive_title_color',
            'asp_design_archive_title_size',
            'asp_design_archive_title_height',
            'asp_design_archive_title_weight',
            'asp_design_excerpt_color',
            'asp_design_excerpt_size',
            'asp_design_excerpt_height',
            'asp_design_excerpt_weight',
            'asp_design_sermon_title_color',
            'asp_design_sermon_title_size',
            'asp_design_sermon_title_height',
            'asp_design_sermon_title_weight',
            'asp_design_sermon_paragraph_color',
            'asp_design_sermon_paragraph_size',
            'asp_design_sermon_paragraph_height',
            'asp_design_sermon_paragraph_weight',
            'asp_design_sermon_details_color',
            'asp_design_pagination_text_color',
            'asp_design_pagination_text_color_hover',
            'asp_design_pagination_text_size',
            'asp_design_pagination_text_height',
            'asp_design_pagination_text_weight',
            'asp_design_pagination_text_padding',
            'asp_design_pagination_background',
            'asp_design_pagination_background_hover',
            'asp_design_pagination_border',
            'asp_design_pagination_border_hover',
            'asp_design_pagination_border_width',
            'asp_design_pagination_border_radius',
            'asp_design_filter_dropdown_text_color',
            'asp_design_filter_dropdown_text_color_hover',
            'asp_design_filter_dropdown_border',
            'asp_design_filter_dropdown_border_hover',
            'asp_design_filter_dropdown_border_width',
            'asp_design_filter_button_text_color',
            'asp_design_filter_button_text_color_hover',
            'asp_design_filter_button_background',
            'asp_design_filter_button_background_hover',
            'asp_design_filter_button_border',
            'asp_design_filter_button_border_hover',
            'asp_design_filter_button_border_width',
            'asp_design_filter_button_border_radius',
            'asp_design_archive_details_color',
            'asp_design_archive_details_link_color',
            'asp_design_archive_details_size',
            'asp_design_archive_details_height',
            'asp_design_archive_details_weight',
            'asp_design_sermon_details_text_color',
            'asp_design_sermon_details_link_color',
            'asp_design_sermon_details_size',
            'asp_design_sermon_details_height',
            'asp_design_sermon_details_weight',
            'asp_design_sermon_image_aspect_ratio',
            'asp_design_series_image_aspect_ratio',
        ],
        'asp-single-sermon-settings' => [
            'asp_single_sermon_content_width',
            'asp_single_sermon_all_sermons_button',
            'asp_single_sermon_archive_button_url',
            'asp_single_sermon_disable_featured_image',
            'asp_single_sermon_default_series_image',
            'asp_single_sermon_disable_comments',
        ],
        'asp-archive-settings' => [
            'asp_archive_sermon_content_width',
            'asp_archive_read_more',
            'asp_archive_pagination_type',
            'asp_archive_excerpt_length',
            'asp_archive_hide_filtering',
            'asp_archive_hide_criteria_box',
            'asp_archive_series_dropdown_orderby',
            'asp_archive_series_dropdown_order',
            'asp_archive_speaker_dropdown_orderby',
            'asp_archive_speaker_dropdown_order',
            'asp_archive_topic_dropdown_orderby',
            'asp_archive_topic_dropdown_order',
            'asp_archive_book_dropdown_orderby',
            'asp_archive_book_dropdown_order',
            'asp_archive_filter_sermon_count',
        ],
        'asp-misc-settings' => [
            'asp_misc_font_awesome',
            'asp_misc_facebook_assets',
            'asp_misc_media_player_style_kit',
        ],
    ];
}

add_action('admin_init', 'asp_register_options');
function asp_register_options() {
    $options = asp_options_array();
    foreach ($options as $option_group => $option_names) {
        foreach ($option_names as $option_name) {
            register_setting($option_group, $option_name);
        }
    }
}
